/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.html or http://ckeditor.com/license
*/
(function(){var i=function(a,f){function i(){var b=arguments,c=this.getContentElement("advanced","txtdlgGenStyle");c&&c.commit.apply(c,b);this.foreach(function(c){c.commit&&"txtdlgGenStyle"!=c.id&&c.commit.apply(c,b)})}var h=function(b){if(!b.originalElement||!b.preview)return 1;b.commitContent(4,b.preview);return 0},l=function(b){var c=b.originalElement;if("true"==c.getCustomData("isReady")){var a=b.getContentElement("info","txtWidth"),d=b.getContentElement("info","txtHeight");a&&a.setValue(c.$.width);
d&&d.setValue(c.$.height)}h(b)},g,e=function(){var b=this.originalElement;b.setCustomData("isReady","true");b.removeListener("load",e);b.removeListener("error",d);b.removeListener("abort",d);this.dontResetSize||l(this);this.firstLoad&&CKEDITOR.tools.setTimeout(function(){},0,this);this.dontResetSize=this.firstLoad=!1},d=function(){var b=this.originalElement;b.removeListener("load",e);b.removeListener("error",d);b.removeListener("abort",d);b=CKEDITOR.getUrl(CKEDITOR.plugins.get("image").path+"images/noimage.png");
this.preview&&this.preview.setAttribute("src",b)},m=CKEDITOR.tools.getNextId()+"_previewLink",k=CKEDITOR.tools.getNextId()+"_previewImage",j=CKEDITOR.tools.getNextId()+"_imageUpload";return{title:a.lang.image["image"==f?"title":"titleButton"],minWidth:420,minHeight:360,onShow:function(){""==$(j).get("html")&&window.parent.uploader.create(j,null);this.linkEditMode=this.imageEditMode=this.linkElement=this.imageElement=!1;this.lockRatio=!0;this.userlockRatio=0;this.dontResetSize=!1;this.firstLoad=!0;
this.addLink=!1;var b=this.getParentEditor(),c=b.getSelection(),a=(c=c&&c.getSelectedElement())&&b.elementPath(c).contains("a",1);g=new CKEDITOR.dom.element("img",b.document);this.preview=CKEDITOR.document.getById(k);this.originalElement=b.document.createElement("img");this.originalElement.setAttribute("alt","");this.originalElement.setCustomData("isReady","false");if(a){this.linkElement=a;this.linkEditMode=!0;var d=a.getChildren();if(1==d.count()){var e=d.getItem(0).getName();if("img"==e||"input"==
e)this.imageElement=d.getItem(0),"img"==this.imageElement.getName()?this.imageEditMode="img":"input"==this.imageElement.getName()&&(this.imageEditMode="input")}"image"==f&&this.setupContent(2,a)}if(c&&"img"==c.getName()&&!c.data("cke-realelement")||c&&"input"==c.getName()&&"image"==c.getAttribute("type"))this.imageEditMode=c.getName(),this.imageElement=c;this.imageEditMode?(this.cleanImageElement=this.imageElement,this.imageElement=this.cleanImageElement.clone(!0,!0),this.setupContent(1,this.imageElement)):
this.imageElement=b.document.createElement("img");CKEDITOR.tools.trim(this.getValueOf("info","txtUrl"))||(this.preview.removeAttribute("src"),this.preview.setStyle("display","none"))},onOk:function(){if(this.imageEditMode){var b=this.imageEditMode;"image"==f&&"input"==b&&confirm(a.lang.image.button2Img)?(this.imageElement=a.document.createElement("img"),this.imageElement.setAttribute("alt",""),a.insertElement(this.imageElement)):"image"!=f&&"img"==b&&confirm(a.lang.image.img2Button)?(this.imageElement=
a.document.createElement("input"),this.imageElement.setAttributes({type:"image",alt:""}),a.insertElement(this.imageElement)):(this.imageElement=this.cleanImageElement,delete this.cleanImageElement)}else"image"==f?this.imageElement=a.document.createElement("img"):(this.imageElement=a.document.createElement("input"),this.imageElement.setAttribute("type","image")),this.imageElement.setAttribute("alt","");this.linkEditMode||(this.linkElement=a.document.createElement("a"));this.commitContent(1,this.imageElement);
this.commitContent(2,this.linkElement);this.imageElement.getAttribute("style")||this.imageElement.removeAttribute("style");this.imageEditMode?!this.linkEditMode&&this.addLink?(a.insertElement(this.linkElement),this.imageElement.appendTo(this.linkElement)):this.linkEditMode&&!this.addLink&&(a.getSelection().selectElement(this.linkElement),a.insertElement(this.imageElement)):this.addLink?this.linkEditMode?a.insertElement(this.imageElement):(a.insertElement(this.linkElement),this.linkElement.append(this.imageElement,
!1)):a.insertElement(this.imageElement)},onLoad:function(){"image"!=f&&this.hidePage("Link");this._.element.getDocument();this.commitContent=i},onHide:function(){this.preview&&this.commitContent(8,this.preview);this.originalElement&&(this.originalElement.removeListener("load",e),this.originalElement.removeListener("error",d),this.originalElement.removeListener("abort",d),this.originalElement.remove(),this.originalElement=!1);delete this.imageElement},contents:[{id:"info",label:a.lang.image.infoTab,
accessKey:"I",elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["280px","110px"],align:"right",children:[{id:"txtUrl",type:"text",label:"Ссылка на изображение",required:!0,onFocus:function(){var b=this.getDialog(),c=this.getValue();if(0<c.length){var b=this.getDialog(),a=b.originalElement;b.preview.removeStyle("display");a.setCustomData("isReady","false");a.on("load",e,b);a.on("error",d,b);a.on("abort",d,b);a.setAttribute("src",c);g.setAttribute("src",c);b.preview.setAttribute("src",
g.$.src);h(b)}else b.preview&&(b.preview.removeAttribute("src"),b.preview.setStyle("display","none"))},onChange:function(){var b=this.getDialog(),c=this.getValue();if(0<c.length){var b=this.getDialog(),a=b.originalElement;b.preview.removeStyle("display");a.setCustomData("isReady","false");a.on("load",e,b);a.on("error",d,b);a.on("abort",d,b);a.setAttribute("src",c);g.setAttribute("src",c);b.preview.setAttribute("src",g.$.src);h(b)}else b.preview&&(b.preview.removeAttribute("src"),b.preview.setStyle("display",
"none"))},setup:function(b,a){if(1==b){var d=a.data("cke-saved-src")||a.getAttribute("src");this.getDialog().dontResetSize=!0;this.setValue(d);this.setInitValue()}},commit:function(b,a){1==b&&(this.getValue()||this.isChanged())?(a.data("cke-saved-src",this.getValue()),a.setAttribute("src",this.getValue())):8==b&&(a.setAttribute("src",""),a.removeAttribute("src"))},validate:CKEDITOR.dialog.validate.notEmpty(a.lang.image.urlMissing)},{type:"button",id:"browse",style:"display:inline-block;margin-top:10px;",
align:"center",label:a.lang.common.browseServer,hidden:!0,filebrowser:"info:txtUrl"}]}]},{id:"txtAlt",type:"text",label:a.lang.image.alt,accessKey:"T","default":"",onChange:function(){h(this.getDialog())},setup:function(b,a){1==b&&this.setValue(a.getAttribute("alt"))},commit:function(b,a){1==b?(this.getValue()||this.isChanged())&&a.setAttribute("alt",this.getValue()):4==b?a.setAttribute("alt",this.getValue()):8==b&&a.removeAttribute("alt")}},{type:"hbox",children:[{type:"vbox",height:"250px",children:[{type:"html",
id:"htmlPreview",style:"width:95%;",html:"<div>"+CKEDITOR.tools.htmlEncode(a.lang.common.preview)+'<br><div class="ImagePreviewBox"><table><tr><td><a href="javascript:void(0)" target="_blank" onclick="return false;" id="'+m+'"><img id="'+k+'" alt="" /></a>'+(a.config.image_previewText||"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas feugiat consequat diam. Maecenas metus. Vivamus diam purus, cursus a, commodo non, facilisis vitae, nulla.")+"</td></tr></table></div></div>"}]}]}]},
{id:"Link",label:a.lang.image.linkTab,padding:0,elements:[{id:"txtUrl",type:"text",label:a.lang.common.url,style:"width: 100%","default":"",setup:function(b,a){if(2==b){var d=a.data("cke-saved-href");d||(d=a.getAttribute("href"));this.setValue(d)}},commit:function(b,c){if(2==b&&(this.getValue()||this.isChanged())){var d=decodeURI(this.getValue());c.data("cke-saved-href",d);c.setAttribute("href",d);if(this.getValue()||!a.config.image_removeLinkByEmptyURL)this.getDialog().addLink=!0}}},{type:"button",
id:"browse",filebrowser:{action:"Browse",target:"Link:txtUrl",url:a.config.filebrowserImageBrowseLinkUrl},style:"float:right",hidden:!0,label:a.lang.common.browseServer},{id:"cmbTarget",type:"select",label:a.lang.common.target,"default":"",items:[[a.lang.common.notSet,""],[a.lang.common.targetNew,"_blank"],[a.lang.common.targetTop,"_top"],[a.lang.common.targetSelf,"_self"],[a.lang.common.targetParent,"_parent"]],setup:function(a,c){2==a&&this.setValue(c.getAttribute("target")||"")},commit:function(a,
c){2==a&&(this.getValue()||this.isChanged())&&c.setAttribute("target",this.getValue())}}]},{id:"Upload",hidden:!1,label:a.lang.image.upload,elements:[{type:"html",id:"htmlImageUpload",html:'<div id="'+j+'"></div>'}]}]}};CKEDITOR.dialog.add("image",function(a){return i(a,"image")});CKEDITOR.dialog.add("imagebutton",function(a){return i(a,"imagebutton")})})();