<?
require_once($_SERVER['DOCUMENT_ROOT'] . "/classes/blogs.php");
require_once($_SERVER['DOCUMENT_ROOT'] . "/classes/employer.php");
require_once($_SERVER['DOCUMENT_ROOT'] . "/classes/freelancer.php");

$blog = new blogs;
$gr = intval(trim($_GET['gr']));
$login = trim($_GET['user']);
$t = trim(__paramInit('string', 't'));
if (!$t) $base = 0; else $base = 1;
$page = intval(trim($_GET['page']));
$from = intval(trim($_GET['from']));
$from = 0; //а нафига вообще тут это нужно?
if (!$page) $page = 1;

if($login) {
    // Личный блог пользователя
    $login = pg_escape_string($login);
    $user = new users();
    $user->GetUser($login);
    if($user->uid && !$user->is_banned) {
        if(!is_emp($user->role)) {
            $user = new freelancer();
            $user->GetUser($login);
            $is_visible = substr($user->tabs,3,1);
        } else {
            $user = new employer();
            $user->GetUser($login);
            $is_visible = substr($user->tabs,2,1);
        }
        $user->GetUser($login);

        if($is_visible) {
            $themes = $blog->GetMsgs($user->uid, $page, $num_msgs, $error, 1);
        }
    }
    $rss_title = "Личные блоги на FL.ru ({$user->login})";
    $rss_link = $host."/rss/blogs.php?user={$user->login}";
    $rss_description = "Личные блоги на сайте www.fl.ru ({$user->login})";
    $gr_name = "Личные блоги";
} else {
    // Общие блоги
    $themes = $blog->GetGroup($gr, $gr_name, $num_msgs, $page, $err, 0, 1, $from, $read_only, "new", false);
    $rss_title = "Блоги на FL.ru ({$gr_name})";
    $rss_link = $host."/rss/blogs.php?gr={$gr}";
    $rss_description = "Блоги на сайте www.fl.ru ({$gr_name})";
}



header("Content-type: application/rss+xml");
echo "<?xml version=\"1.0\" encoding=\"windows-1251\"?>
<!--  RSS generated by FL.ru RSS Generator on ".date("D, d M Y H:i:s")." GMT+3 -->
" ; ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title><?=$rss_title?></title>
<link><?=$rss_link?></link> 
<description><?=$rss_description?></description> 
<language>ru-ru</language> 
<pubDate><?=date("D, d M Y H:i:s")." GMT+3"?></pubDate>
<lastBuildDate><?=date("D, d M Y H:i:s",strtotimeEx($themes[0]['post_time']))." GMT+3"?></lastBuildDate> 
<docs>http://blogs.law.harvard.edu/tech/rss</docs> 
<generator>FL.ru RSS Generator</generator>
<category><?=$gr_name?></category>
<ttl>30</ttl> 
<image>
	<url><?=$host?>/images/free-lance_logo.jpg</url>
	<title>Блоги на FL.ru (<?=$gr_name?>)</title>
	<link><?=$host?></link> 
	<width>113</width>
	<height>18</height>
</image>
<managingEditor>info@fl.ru</managingEditor>
<webMaster>info@fl.ru</webMaster>
<?
if ($themes){ 
    $i = 0;
    foreach($themes as $ikey=>$theme){
        /*if ( $theme['moderator_status'] === '0' ) {
            continue;
        }*/
?>
    	<item>
    	<title><?=preg_replace(array("/&/","/</","/>/"),array("&#x26;","&#x3C;","&#x3E;"),html_entity_decode($theme['title'], ENT_QUOTES, 'cp1251'))?></title> 
	<link><?=$host?><?=getFriendlyUrl('blog',$theme['thread_id'])?></link> 
    	<description><![CDATA[<?=xmloutofrangechars(reformat($theme['msgtext'], 96, 1))?>]]></description>
    	<guid><?=md5($theme['post_time'].'-'.$theme['id'])?></guid>
    	<pubDate><?=date("D, d M Y H:i:s",strtotimeEx($theme['post_time']))." GMT+3"?></pubDate>
    	<comments><?=$host?><?=getFriendlyUrl('blog',$theme['thread_id'])?></comments>
    	</item>
<?
    }
}
?>
</channel>
</rss>
