<?
require_once($_SERVER['DOCUMENT_ROOT'] . "/classes/blogs.php");
$blog = new blogs;//blogs;

list($themes, $usr) = $blog->getCorporateBlog();
if ($themes){ 
header("Content-type: application/rss+xml");
echo "<?xml version=\"1.0\" encoding=\"windows-1251\"?>
<!--  RSS generated by FL.ru RSS Generator on ".gmdate("D, d M Y H:i:s")." GMT -->
" ; ?>
<rss version="2.0">
<channel>
<title>Корпоративный блог на FL.ru</title>
<link><?=$host?>/rss/corporative.php</link> 
<description>Корпоративный блог на сайте www.fl.ru</description> 
<language>ru-ru</language> 
<pubDate><?=gmdate("D, d M Y H:i:s")?></pubDate>
<lastBuildDate><?=gmdate("D, d M Y H:i:s",strtotimeEx($themes[0]['date_create']))?></lastBuildDate> 
<docs>http://blogs.law.harvard.edu/tech/rss</docs> 
<generator>FL.ru RSS Generator</generator>
<category>Корпоративный блог</category>
<ttl>30</ttl> 
<image>
	<url><?=$host?>/images/free-lance_logo.jpg</url>
	<title>Корпоративный блог на FL.ru</title>
	<link><?=$host?></link> 
	<width>113</width>
	<height>18</height>
</image>
<managingEditor>info@fl.ru</managingEditor>
<webMaster>info@fl.ru</webMaster>
<? foreach($themes as $ikey=>$theme): ?>
	<item>
		<title><?=$theme['title']?></title> 
		<author><?=$usr[$theme['id_user']]['uname']." ".$usr[$theme['id_user']]['usurname']. "[".$usr[$theme['id_user']]['login']."]"?></author>
		<link><?=$host?>/about/corporative/post/<?=$theme['id']?>/</link> 
		<description><![CDATA[<?=reformat($theme['msg'], 96, 1)?>]]></description>
		<guid><?=$host?>/about/corporative/</guid>
		<pubDate><?=gmdate("D, d M Y H:i:s",strtotimeEx($theme['date_create']))?></pubDate>
		<comments><?=$host?>/about/corporative/post/<?=$theme['id']?>/</comments>
	</item>
<? endforeach; }?>
</channel>
</rss>