<?php
  require_once($_SERVER['DOCUMENT_ROOT'] . "/classes/projects.php");
  require_once($_SERVER['DOCUMENT_ROOT'] . "/classes/professions.php");

  switch($kind) {
      case 0 :
      case 1 : $kindStr = 'Фри-ланс'; $kind = 1; break;
      case 2 : $kindStr = 'Конкурсы'; break;
      case 4 : $kindStr = 'В офис'; break;
      case 6 : $kindStr = 'Проекты для PRO'; break;
      default: $kindStr = 'Все проекты'; $kind = 5; break;
  }
  if(!$subcategory) $subcategory = 0;
  $mbkey = $subcategory ? ($category ? $category.'_' : '').'sub_'.$subcategory : $category;

  $projects = new new_projects();
  $projects->setPageSize(new_projects::PAGE_SIZE_RSS);

  $getcnt = 'nenado';
  $additional = $subcategory
        ? array('active'=>'t', 'categories'=>array(array(),array($subcategory=>1)))
        : ($category ? array('active'=>'t', 'categories'=>array(array($category=>1))) : null);
  $prjs = $projects->getProjects( $getcnt, (int)$kind, 1, false, $additional);

  if($subcategory){
      $kindStr .= ": ".professions::GetProfNameWP($subcategory, ' - ', 'Все разделы', false);
  }elseif($category) {
      $name_cat = professions::GetGroup($category, $error);
      $kindStr .= ': '.$name_cat['name'];
  }
  
  header('Content-Type: application/rss+xml');
  print('<?xml version="1.0" encoding="windows-1251"?>');
?>
<!--  RSS generated by FL.ru RSS Generator on <?=gmdate("D, d M Y H:i:s")?> GMT -->
<rss version="2.0">
<channel>
  <title>Проекты на FL.ru (<?=$kindStr?>)</title>
  <link><?=$host?></link>
  <description>Проекты/Предложения на сайте www.fl.ru (Удаленная работа)</description> 
  <language>ru-ru</language> 
  <pubDate><?=gmdate("D, d M Y H:i:s")?> GMT</pubDate>
  <lastBuildDate><?=gmdate("D, d M Y H:i:s")?> GMT</lastBuildDate> 
  <docs>http://blogs.law.harvard.edu/tech/rss</docs> 
  <generator>FL.ru RSS Generator</generator> 
  <image>
    <url><?=$host?>/images/free-lance_logo.jpg</url>
    <title><![CDATA[Проекты на FL.ru (<?=$kindStr?>)]]></title>
    <link><?=$host?></link> 
    <width>113</width>
    <height>18</height>
  </image>
  <managingEditor>info@fl.ru</managingEditor>
  <webMaster>info@fl.ru</webMaster>
  <? 
  if ( $prjs ) {
    foreach ($prjs as $ikey=>$prj)
    { 
        /*if ( $prj['moderator_status'] === '0' ) {
            continue;
        }*/
        
      $prj['descr'] = str_replace("&quot;", '"', $prj['descr']);
      $prj['descr'] = xmloutofrangechars( $prj['descr'] );
      $prj['name']  = html_entity_decode($prj['name'], ENT_QUOTES, 'cp1251');
      $prj['name']  = xmloutofrangechars( $prj['name'] );
      $prj_cost = str_replace("&euro;", "Euro", view_cost2($prj['cost'], '', '', false, $prj['currency']));
      $prj_link = HTTP_PREFIX.$_SERVER["HTTP_HOST"].getFriendlyUrl('project',$prj['id']);
  ?>
    <item>
      <title><![CDATA[<?=$prj['name'].($prj['cost'] > 0 ? " (Бюджет: {$prj_cost})" : '')?>]]></title> 
      <link><?=$prj_link?></link>
      <? if ($prj['pro_only'] == "t") { ?>
      <?/*<description>Описание проекта доступно только для PRO.</description>*/?>
      <description><![CDATA[<?=str_replace('<br', '<br /', LenghtFormatEx($prj['descr'],180))?>]]></description>
      <? } else { ?>
      <description><![CDATA[<?=str_replace('<br', '<br /', $prj['descr'])?>]]></description>
      <? } ?>
      <guid><?=$prj_link?></guid>
      <category><![CDATA[<?=$projects->getSpecsStr($prj['id'],' / ',']]></category><category><![CDATA[');?>]]></category>
      <pubDate><?=gmdate('D, d M Y H:i:s', strtotimeEx($prj['post_date']))?> GMT</pubDate>
    </item>
  <?
    }
  }
  ?>
</channel>
</rss>