<td>&nbsp;</td>
<td class="b-layout__td b-layout__td_padbot_20" colspan="2">
    <div class="b-check b-check_padtop_10">
        <input <?php if ($this->element->isChecked()):?>checked<?php endif;?> type="checkbox" value="1" name="<?php echo $this->element->getName();?>" class="b-check__input" id="b-check2">
        <label class="b-check__label b-check__label_fontsize_13" for="b-check2"><?php print $this->element->getLabel();?></label>
    </div>
</td>