<td class="b-layout__td b-layout__td_width_120 b-layout__td_padbot_<?=$this->element->getAttrib('padbot')?$this->element->getAttrib('padbot'):20?>">
    <div class="b-layout__txt b-layout__txt_fontsize_15"><?=$this->element->getLabel();?></div>
</td>
<td class="b-layout__td b-layout__td_padbot_<?=is_numeric($this->element->getAttrib('padbot'))?$this->element->getAttrib('padbot'):20?>">
 
    <div id="apf-files" style="position:relative;">
        <div id="attachedfiles" class=""></div>
        <div class="b-layout__txt b-layout__txt_fontsize_11 b-layout__txt_padtop_5">
            Загрузите документ или иллюстрацию, дающую дополнительную информацию о проекте и задаче
        </div>
    </div>
<?php

$values = $this->element->getValue();
if ($values) {
    $values = is_array($values)?$values[0]:$values;
} else {
    $values = uploader::createResource('guest_prj');
}

$uploader = new uploader($values);

$templates = array(
    uploader::getTemplate('uploader', 'project/'),
    uploader::getTemplate('uploader.file', 'project/'),
    uploader::getTemplate('uploader.popup', '')
);
uploader::init(array(
    'attachedfiles'  => uploader::sgetLoaderOptions($uploader->resource)
), $templates);

?>
</td>