<td class="b-layout__td 
    b-layout__td_width_<?=$this->element->getAttrib('label_width')?$this->element->getAttrib('label_width'):120?> 
    b-layout__td_padbot_<?=$this->element->getAttrib('padbot')?$this->element->getAttrib('padbot'):20?>">
    <div class="b-layout__txt b-layout__txt_fontsize_15"><?=$this->element->getLabel();?></div>
</td>
<td class="b-layout__td b-layout__td_padbot_<?=is_numeric($this->element->getAttrib('padbot'))?$this->element->getAttrib('padbot'):20?>">
    <div class="b-combo 
        <?php if($this->element->getAttrib('unit')):?>b-combo_inline-block<?php endif; ?>">
        <div class="b-combo__input 
            <?php if ($this->element->getAttrib('width')):?>b-combo__input_width_<?=$this->element->getAttrib('width')?><?php endif?>
            <?php if($this->element->hasErrors()): ?>b-combo__input_error<?php endif;?>">
            <input 
                id="el-<?=$this->element->getName();?>"
                type="text" 
                name="<?=$this->element->getName();?>" 
                value="<?=htmlspecialchars(stripslashes($this->element->getValue()));?>" 
                <?php if ($this->element->getAttrib('width')):?>size="<?=$this->element->getAttrib('width')?>"<?php endif?> 
                <?php if ($this->element->getAttrib('maxlength')):?>maxlength="<?=$this->element->getAttrib('maxlength')?>"<?php endif?> 
                <?php if ($this->element->getAttrib('placeholder')):?>placeholder="<?=htmlspecialchars($this->element->getAttrib('placeholder'))?>"<?php endif?> 
                class="b-combo__input-text">
        </div>
    </div>
    
    <?php if ($this->element->getAttrib('unit')): ?>
    <div class="b-layout__txt b-layout__txt_padleft_10 b-layout__txt_padtop_2 b-layout__txt_inline-block b-layout__txt_fontsize_15">
        <?=$this->element->getAttrib('unit')?>
    </div>
    <?php endif; ?>
    
    <?php if ($this->element->getAttrib('suffix')): ?>
        <div class="b-layout__txt b-layout__txt_fontsize_11 b-layout__txt_padtop_2">
            <?=$this->element->getAttrib('suffix')?>
        </div>
    <?php endif; ?>

    <div class="b-layout__txt b-layout__txt_padtop_5 b-layout__txt_color_c10600 <?php if (!$this->element->hasErrors()): ?>b-layout_hide<?php endif;?>" 
        id="el-<?=$this->element->getName();?>-error">
        <span class="b-icon b-icon_sbr_rattent"></span>
        <span id="el-<?=$this->element->getName();?>-error-text"><?=array_shift($this->element->getMessages()); ?></span>
    </div>
</td>