<?php if($this->element->getAttrib('padbot')): ?>
<td class="b-layout__td b-layout__td_padbot_<?=$this->element->getAttrib('padbot')?>">
<?php endif; ?>
    <?php if(!$this->element->getAttrib('hide_label')):?>
    <div class="
         b-layout__txt 
         b-layout__txt_padbot_<?=$this->element->getAttrib('label_padbot')?$this->element->getAttrib('label_padbot'):'10'?>
         b-layout__txt_bold 
         b-layout__txt_fontsize_<?=$this->element->getAttrib('label_fs')?$this->element->getAttrib('label_fs'):'13'?>">
        <?=$this->element->getLabel();?>
    </div>
    <?php endif;?>
    <div class="b-combo 
      <?php if($this->element->getAttrib('unit')):?>b-combo_inline-block<?php endif; ?>">
      <div class="
           b-combo__input 
           b-combo__input_multi_dropdown 
           <?php if($this->element->getDbId() > 0):?>drop_down_default_<?=$this->element->getDbId()?><?php endif; ?> 
           <?=$this->element->getAttrib('class')?>">

         <input type="hidden" 
                name="el-<?=$this->element->getName();?>_columns[0]" 
                value="<?=$this->element->getColumnId(0)?>">
         <input type="hidden" 
                name="el-<?=$this->element->getName();?>_columns[1]" 
                value="<?=$this->element->getColumnId(1)?>">

         <input id="el-<?=$this->element->getName();?>"
                type="text" 
                name="<?=$this->element->getName();?>" 
                value="<?=htmlspecialchars(stripslashes($this->element->getUnfilteredValue()));?>" 
                <?php if ($this->element->getAttrib('width')):?>size="<?=$this->element->getAttrib('width')?>"<?php endif?> 
                <?php if ($this->element->getAttrib('maxlength')):?>maxlength="<?=$this->element->getAttrib('maxlength')?>"<?php endif?> 
                <?php if ($this->element->getAttrib('placeholder')):?>placeholder="<?=htmlspecialchars($this->element->getAttrib('placeholder'))?>"<?php endif?> 
                class="b-combo__input-text"/>
         <label for="el-<?=$this->element->getName();?>" class="b-combo__label">
                <?=htmlspecialchars(stripslashes($this->element->getUnfilteredValue()));?>
         </label>
         <span class="b-combo__arrow"></span>
      </div>
    </div>

    <?php if ($this->element->getAttrib('suffix')): ?>
        <div class="b-layout__txt b-layout__txt_fontsize_11 b-layout__txt_padtop_2">
            <?=$this->element->getAttrib('suffix')?>
        </div>
    <?php endif; ?>

    <div class="b-layout__txt b-layout__txt_padtop_5 b-layout__txt_color_c10600 <?php if (!$this->element->hasErrors()): ?>b-layout_hide<?php endif;?>" 
        id="el-<?=$this->element->getName();?>-error">
        <span class="b-icon b-icon_sbr_rattent"></span>
        <span id="el-<?=$this->element->getName();?>-error-text"><?=array_shift($this->element->getMessages()); ?></span>
    </div>
<?php if($this->element->getAttrib('padbot')): ?>
</td>
<?php endif; ?>