<?php if($this->element->getAttrib('padbot')): ?>
<td class="b-layout__td b-layout__td_padbot_<?=$this->element->getAttrib('padbot')?>">
<?php endif; ?>
    <?php if(!$this->element->getAttrib('hide_label')):?>
    <div class="
         b-layout__txt 
         b-layout__txt_padbot_<?=$this->element->getAttrib('label_padbot')?$this->element->getAttrib('label_padbot'):'10'?>
         b-layout__txt_bold 
         b-layout__txt_fontsize_<?=$this->element->getAttrib('label_fs')?$this->element->getAttrib('label_fs'):'13'?>">
        <?=$this->element->getLabel();?>
    </div>
    <?php endif;?>
    <?php

    $options = $this->element->getMultiOptions();
    $values = (array) $this->element->getValue();
    $cnt = count($options);
    if($cnt):
        $idx = 0;
        foreach($options as $key => $value): 
            $optId = "el-{$this->element->getName()}-{$idx}";
    ?>
    <div class="b-check <?php if($idx): ?>b-check_padtop_15<?php endif; ?>">
        <input type="checkbox" 
               <?php if (in_array($key, $values)):?>checked="checked"<?php endif; ?>               
               value="<?=htmlspecialchars($key);?>" 
               name="<?php echo $this->element->getName();?>[]" 
               class="b-check__input" 
               id="<?=$optId?>">
        <label class="b-check__label b-check__label_fontsize_13" for="<?=$optId?>">
            <?=$value?>
        </label>
    </div>
    <?php
            $idx++;
        endforeach;
    endif;
    ?>
    <?php if ($this->element->getAttrib('suffix')): ?>
        <div class="b-layout__txt b-layout__txt_fontsize_11 b-layout__txt_padtop_2">
            <?=$this->element->getAttrib('suffix')?>
        </div>
    <?php endif; ?>

    <div class="b-layout__txt b-layout__txt_padtop_5 b-layout__txt_color_c10600 <?php if (!$this->element->hasErrors()): ?>b-layout_hide<?php endif;?>" 
        id="el-<?=$this->element->getName();?>-error">
        <span class="b-icon b-icon_sbr_rattent"></span>
        <span id="el-<?=$this->element->getName();?>-error-text"><?=array_shift($this->element->getMessages()); ?></span>
    </div>
<?php if($this->element->getAttrib('padbot')): ?>
</td>
<?php endif; ?>