<?php if($this->element->getAttrib('padbot')): ?>
<td class="b-layout__td b-layout__td_padbot_<?=$this->element->getAttrib('padbot')?> <?php if ($this->element->getAttrib('td_class')): echo $this->element->getAttrib('td_class'); endif;?>">
<?php endif; ?>
    <?php if(!$this->element->getAttrib('hide_label')):?>
    <div class="
         b-layout__txt <?php if ($this->element->getAttrib('label_class')): echo $this->element->getAttrib('label_class'); else:?>
         b-layout__txt_padbot_<?=$this->element->getAttrib('label_padbot')?$this->element->getAttrib('label_padbot'):'10'?>
         b-layout__txt_bold 
         b-layout__txt_fontsize_<?=$this->element->getAttrib('label_fs')?$this->element->getAttrib('label_fs'):'13'?><?php endif; ?>">
        <?=$this->element->getLabel();?>
    </div>
    <?php endif;?>
    <div class="b-combo <?php if ($this->element->getAttrib('class')): echo $this->element->getAttrib('class'); endif;?> <?php if ($this->element->getAttrib('unit')):?>b-combo_inline-block<?php endif; ?>">
        <div class="b-combo__input  
            <?php if ($this->element->getAttrib('width')):?>b-combo__input_width_<?=$this->element->getAttrib('width')?><?php endif?>
            <?php if($this->element->hasErrors()): ?>b-combo__input_error<?php endif;?>">
            <input 
                <?php if ($this->element->getAttrib('data-validators')):?>data-validators="<?=$this->element->getAttrib('data-validators')?>"<?php endif?> 
                id="el-<?=$this->element->getName();?>"
                type="text" 
                name="<?=$this->element->getName();?>" 
                value="<?=htmlspecialchars(stripslashes($this->element->getValue()));?>" 
                <?php if ($this->element->getAttrib('width')):?>size="<?=$this->element->getAttrib('width')?>"<?php endif?> 
                <?php if ($this->element->getAttrib('maxlength')):?>maxlength="<?=$this->element->getAttrib('maxlength')?>"<?php endif?> 
                <?php if ($this->element->getAttrib('placeholder')):?>placeholder="<?=htmlspecialchars($this->element->getAttrib('placeholder'))?>"<?php endif?> 
                class="b-combo__input-text">
        </div>
    </div>
    <div class="b-layout__txt 
         b-layout__txt_left 
         b-layout__txt_float_left 
         b-layout__txt_padtop_5 
         b-layout__txt_color_c10600 
         <?php if ($this->element->getAttrib('error_class')): echo $this->element->getAttrib('error_class'); endif;?> 
         <?php if (!$this->element->hasErrors()): ?>b-layout_hide<?php endif;?>" 
         id="el-<?=$this->element->getName();?>-error">
         <span class="b-icon b-icon_sbr_rattent"></span>
         <span id="el-<?=$this->element->getName();?>-error-text">
            <?=array_shift($this->element->getMessages()); ?>
         </span>
    </div>
<?php if($this->element->getAttrib('padbot')): ?>
</td>
<?php endif; ?>
